"""initial schema

Revision ID: 3b17d2cce51c
Revises: 
Create Date: 2026-08-27 20:13:19.700879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b17d2cce51c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Enum('FREE', 'PRO', name='plantier', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('api_call_quota', sa.BigInteger(), nullable=False),
    sa.Column('ai_token_quota', sa.BigInteger(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_stripe_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_stripe_events_event_type'), 'processed_stripe_events', ['event_type'], unique=False)
    op.create_index('ix_processed_stripe_events_type_time', 'processed_stripe_events', ['event_type', 'processed_at'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.Enum('FREE', 'PRO', name='plantier', native_enum=False), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'INCOMPLETE', 'TRIALING', name='subscriptionstatus', native_enum=False), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subscriptions_stripe_id', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=True)
    op.create_table('usage_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('usage_type', sa.Enum('API_CALL', 'INPUT_TOKENS', 'CACHED_INPUT_TOKENS', 'OUTPUT_TOKENS', 'REASONING_TOKENS', name='usagetype', native_enum=False), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('cost_microunits', sa.BigInteger(), nullable=False),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', 'usage_type', name='uq_tenant_idempotency_usage_type')
    )
    op.create_index(op.f('ix_usage_events_tenant_id'), 'usage_events', ['tenant_id'], unique=False)
    op.create_index('ix_usage_events_tenant_month', 'usage_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_usage_events_tenant_type_month', 'usage_events', ['tenant_id', 'usage_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_usage_type'), 'usage_events', ['usage_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_events_usage_type'), table_name='usage_events')
    op.drop_index('ix_usage_events_tenant_type_month', table_name='usage_events')
    op.drop_index('ix_usage_events_tenant_month', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_tenant_id'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index('ix_subscriptions_stripe_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_tenants_stripe_customer_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_processed_stripe_events_type_time', table_name='processed_stripe_events')
    op.drop_index(op.f('ix_processed_stripe_events_event_type'), table_name='processed_stripe_events')
    op.drop_table('processed_stripe_events')
    op.drop_table('plans')
    # ### end Alembic commands ###
